# 基础镜像
FROM python:3.9-slim

# 1. 换源并安装系统依赖 (关键：增加了 zstd 和 lz4)
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get install -y \
    liblz4-dev \
    zlib1g-dev \
    brotli \
    iproute2 \
    zstd \
    lz4 \
    && rm -rf /var/lib/apt/lists/*

# 2. 安装Python依赖
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple \
    zstandard==0.19.0 \
    lz4==4.0.0 \
    psutil==5.9.0 \
    py-cpuinfo==9.0.0 \
    brotli==1.0.9

# 设置工作目录
WORKDIR /app

# 【关键修改】修正复制路径
# 因为构建要在根目录进行，而脚本在 ml_training 文件夹里
COPY ml_training/client_agent.py .

# 3. 容器默认挂机
CMD ["tail", "-f", "/dev/null"]